### ISSUE TITLE
timers.unenroll() deprecated

### ISSUE THREAD

**Issue by ralphtheninja** [mafintosh/utp-native#24]
Originally reported here https://github.com/cabal-club/cabal/issues/10

Same goes for `timers.enroll()`. I don't really understand how this works so don't have any suggestion how to rewrite this. If you give me some pointers I could try and fix it.

**Comment by mafintosh** [comment]
https://github.com/nodejs/node/pull/20298 - need to move to something like that when avail

**Comment by joehand** [comment]
It's available now =)

**Comment by mafintosh** [comment]
fixed in latest
