### ISSUE TITLE
Supported engines?

### ISSUE THREAD

**Issue by staltz** [mafintosh/utp-native#27]
Because of the N-API rewrite and use of napi_fatal_exception, I *think* this package now only supports Node v10 and above. Would help with troubleshooting to have listed this requirement in package.json and/or readme.

**Comment by mafintosh** [comment]
Yes good idea. The fatal exception handler was backported to 8 in https://nodejs.org/en/blog/release/v8.11.2/

**Comment by mafintosh** [comment]
fixed in latest
