### ISSUE TITLE
N-API warning

### ISSUE THREAD

**Issue by hackergrrl** [mafintosh/utp-native#31]
I *think* it's utp-native that triggers this message to stderr whenever I start a node app using it:

```
(node:6215) Warning: N-API is an experimental feature and could change at any time.
```

Is there a way to suppress this from this module?

**Comment by mafintosh** [comment]
Upgrade to Node 10. It was stabilized there.

**Comment by noffle** [comment]
It'd be great to have a fix for everyone who hasn't upgraded & will see this warning & not know they need to upgrade just because somewhere in the dep tree there's utp-native.

**Comment by mafintosh** [comment]
Define "fix" 😆 😄

**Comment by mafintosh** [comment]
There is a flag to suppress on 8, called --experimental-node-api or something like that. see --help

**Comment by noffle** [comment]
In this case, "fix" would mean suppressing the warning text.

**Comment by mafintosh** [comment]
Closing because n-api is very supported everywhere atm :)
