### ISSUE TITLE
UncaughtReferenceError: require is not defined at Object ./node_modules/utp-native/Lib/binding.js

### ISSUE THREAD

**Issue by marcoippolito** [mafintosh/utp-native#36]
I installed utp-native:

    (base) marco@pc01:~/webMatters/vueMatters/GGC$ yarn add utp-native
    yarn add v1.22.4
    $ npx npm-force-resolutions
    npx: installed 5 in 0.767s
    warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix    
    package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning,   
    remove package-lock.json.
    [1/4] Resolving packages...
    warning Resolution field "minimist@1.2.5" is incompatible with requested version "minimist@1.2.0"
    [2/4] Fetching packages...
    warning Pattern ["esprima-fb@~3001.0001.0000-dev-harmony-fb"] is trying to unpack in the same destination "/home/marco
    /.cache/yarn/v6/npm-esprima-fb-3001.1.0-dev-harmony-fb-b77d37abcd38ea0b77426bb8bc2922ce6b426411-integrity
    /node_modules/esprima-fb" as pattern ["esprima-fb@~3001.1.0-dev-harmony-fb"]. This could result in non-deterministic 
    behavior, skipping.
    warning Pattern ["utp-native@^2.2.1"] is trying to unpack in the same destination "/home/marco/.cache/yarn/v6/npm-utp-native-
    2.2.1-6d33feba04bfe49b368bad05555703f9728b6e63-integrity/node_modules/utp-native" as pattern ["utp-native@^2.1.7","utp-
    native@^2.2.1"]. This could result in non-deterministic behavior, skipping.
    info fsevents@2.1.3: The platform "linux" is incompatible with this module.
    info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
    info fsevents@1.2.13: The platform "linux" is incompatible with this module.
    info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
    [3/4] Linking dependencies...
    warning " > bootstrap@4.5.0" has unmet peer dependency "jquery@1.9.1 - 3".
    warning " > bootstrap@4.5.0" has unmet peer dependency "popper.js@^1.16.0".
    warning " > gun@0.2020.520" has unmet peer dependency "@gooddollar/react-native-webview-crypto@^0.*".
    warning " > gun@0.2020.520" has unmet peer dependency "bufferutil@^4.0.1".
    warning " > gun@0.2020.520" has unmet peer dependency "utf-8-validate@^5.0.2".
    warning "http-proxy-middleware > http-proxy > follow-redirects@1.12.0" has unmet peer dependency "debug@^3.0.0 || ^4.0.0".
    warning " > rxdb@9.3.0" has unmet peer dependency "rxjs@^6.5.4".
    warning "tiptap-extensions > prosemirror-utils@0.9.6" has incorrect peer dependency "prosemirror-tables@^0.9.1".
    warning " > y-prosemirror@0.3.5" has unmet peer dependency "y-protocols@^0.2.0".
    warning " > y-prosemirror@0.3.5" has unmet peer dependency "prosemirror-model@^1.7.1".
    warning " > y-prosemirror@0.3.5" has unmet peer dependency "prosemirror-state@^1.2.3".
    warning " > y-prosemirror@0.3.5" has unmet peer dependency "prosemirror-view@^1.9.10".
    [4/4] Building fresh packages...
    success Saved 0 new dependencies.
    $ electron-builder install-app-deps
      • electron-builder  version=22.7.0
      • rebuilding native dependencies  dependencies=abstract-socket@2.1.1, better-sqlite3@5.4.3, bufferutil@4.0.1,  
    canvas@2.6.1, fd-lock@1.1.1, integer@2.1.0, sodium-native@3.2.0, utf-8-validate@5.0.2, utp-native@2.2.1,  
    websocket@1.0.31, sodium-native@2.4.9, sodium-native@2.4.9, sodium-native@2.4.9, sodium-native@2.4.9
                                        platform=linux
                                        arch=x64
      • rebuilding native dependency  name=better-sqlite3 version=5.4.3
      • rebuilding native dependency  name=abstract-socket version=2.1.1
      • rebuilding native dependency  name=bufferutil version=4.0.1
      • rebuilding native dependency  name=canvas version=2.6.1
      • rebuilding native dependency  name=fd-lock version=1.1.1
      • rebuilding native dependency  name=integer version=2.1.0
      • rebuilding native dependency  name=sodium-native version=3.2.0
      • rebuilding native dependency  name=utf-8-validate version=5.0.2
      • rebuilding native dependency  name=utp-native version=2.2.1
      • rebuilding native dependency  name=websocket version=1.0.31
      • rebuilding native dependency  name=sodium-native version=2.4.9
      • rebuilding native dependency  name=sodium-native version=2.4.9
      • rebuilding native dependency  name=sodium-native version=2.4.9
      • rebuilding native dependency  name=sodium-native version=2.4.9
    Done in 46.38s.

In UtpNative.vue file I put: 

    <script>

        import utp from 'utp-native';
        const server = utp.createServer(function (socket) {
          socket.pipe(socket) // echo server
        })

        server.listen(10000, function () {
          const socket = utp.connect(10000)

          socket.write('hello world')
          socket.end()

          socket.on('data', function (data) {
            console.log('echo: ' + data)
          })
          socket.on('end', function () {
            console.log('echo: (ended)')
          })
        })

But when running the app I get this errors message:

    "UncaughtReferenceError: require is not defined at Object ./node_modules/utp-native/Lib/binding.js"

![image](https://user-images.githubusercontent.com/3073209/88075013-810f5080-cb78-11ea-8f2e-15f78c18177c.png)

    Environment Info:

      System:
        OS: Linux 5.3 Ubuntu 18.04.4 LTS (Bionic Beaver)
        CPU: (8) x64 Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
      Binaries:
        Node: 14.3.0 - ~/.nvm/versions/node/v14.3.0/bin/node
        Yarn: 1.22.4 - /usr/bin/yarn
        npm: 6.14.5 - ~/.nvm/versions/node/v14.3.0/bin/npm
      Browsers:
        Chrome: 84.0.4147.89
        Firefox: 78.0.2
      npmGlobalPackages:
        @vue/cli: 4.4.4

How to solve the problem?
Marco

**Comment by mafintosh** [comment]
I don't know enough about your environment to help you with that. Looks like require is not defined?

**Comment by marcoippolito** [comment]
Which aspects of my environment could influence and impact on the correct installation of utp-native?

**Comment by mafintosh** [comment]
@marcoippolito you need a nodejs env that exposes the require method

**Comment by marcoippolito** [comment]
> @marcoippolito you need a nodejs env that exposes the require method

Actually I've been using 'import' method.
But I made a quick test with 'require' method and it seems working:

    <template>
      <div>
        <input v-model="n" placeholder="value">
        <p>SquaredValue: {{squaredN}}</p>
      </div>
    </template>

    <script>

    //import { abc } from './abc';
    const abc = require('./abc');

    export default {
      data() {
        return {
          n: 0,
        }
      },
      computed: {
        squaredN: function(){
          return abc.squared(this.n);
        }
      }
    }
    </script>


![image](https://user-images.githubusercontent.com/3073209/88408636-1e19f580-cdd4-11ea-95a1-57a0b038e52e.png)

Is this what you meant as "nodejs env that exposes the require method" ?

**Comment by mafintosh** [comment]
Yep. Your error above says no require method available, which means something in your env is not defining it. Thats the bug

**Comment by marcoippolito** [comment]
But I do not understand why then, if in my env the require method is not available,  

    const abc = require('./abc');

works fine

**Comment by mafintosh** [comment]
I don’t know, but it I’d suggest to debug your webpack setup to figure this out :)

**Comment by mafintosh** [comment]
Closing as this is unrelated to utp-native.
