### ISSUE TITLE
Help Please. Problem with UTP on VPS Ubuntu 18.04

### ISSUE THREAD

**Issue by jczasgit** [mafintosh/utp-native#44]
I am getting the following error.
```
Error: invalid argument
    at Connection._connect (/mnt/sdb/svr/synchronos/node_modules/utp-native/lib/connection.js:197:11)
    at /mnt/sdb/svr/synchronos/node_modules/utp-native/lib/connection.js:189:10
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
    at runNextTicks (node:internal/process/task_queues:63:3)
    at listOnTimeout (node:internal/timers:526:9)
    at processTimers (node:internal/timers:500:7) {
  code: 'EINVAL'
}
```
I am using [WebTorrent](https://github.com/webtorrent/webtorrent) to download an mp4 file. It all works well on my local Windows 10 machine and even my raspberry pi 4 (Ubuntu 20.04), but it fails on the VPS (Ubuntu 18.04).
I am very new to network protocols in general. Can someone help me out?

**Comment by nuzzesick** [comment]
I'm having the same problem on MacOS Silicon. Please help!!!

**Comment by mafintosh** [comment]
Can you share a but more info? Which utp version, node/electron version?

**Comment by jczasgit** [comment]
> Can you share a but more info? Which utp version, node/electron version?

I am using both node version 15.14.0 on ubuntu server and my local windows 10 machine. The version of utp-native is 2.4.0. The package is a dependency of  [WebTorrent](https://github.com/webtorrent/webtorrent) package, so I am not sure how they used it. I will have to dive into the source code to know.

**Comment by mafintosh** [comment]
Looks to me like webtorrent is passing some invalid arguments to utp.connect(port, host) (something is at least).

I'd open an issue there, or if you can provide more tracing etc then I'll try to help.

**Comment by mafintosh** [comment]
It is probably passing an invalid ip like so:

```
require('utp-native').connect(0, '555.555.555.555') // throws as the ip is invalid
```

**Comment by mafintosh** [comment]
we can also catch that here and forward it as an error, if anyone is interested in helping it means improving my isIP method here https://github.com/mafintosh/utp-native/blob/master/index.js#L274 to be more strict (ie [1-255].[0-255].[0-255].[0.255]) - PR super welcome without pulling in any more deps :)

**Comment by nuzzesick** [comment]
@mafintosh check this: https://github.com/webtorrent/webtorrent/issues/2114
apparently the bug comes from webtorrent !

**Comment by jczasgit** [comment]
> we can also catch that here and forward it as an error, if anyone is interested in helping it means improving my isIP method here https://github.com/mafintosh/utp-native/blob/master/index.js#L274 to be more strict (ie [1-255].[0-255].[0-255].[0.255]) - PR super welcome without pulling in any more deps :)

I read the line of code and it could be improved. Right now I believe that it accepts any format of 1-3 digits. I am very new to this so I am not sure if ipv4 addresses only go up to 255. I can do some research and make a PR.

**Comment by jczasgit** [comment]
> @mafintosh check this: [webtorrent/webtorrent#2114](https://github.com/webtorrent/webtorrent/issues/2114)
> apparently the bug comes from webtorrent !

A workaround https://github.com/webtorrent/webtorrent/issues/2114#issuecomment-871046916
I do not believe this is the way to handle this. Definitely needs more work.

**Comment by jczasgit** [comment]
Closing this issue because the workaround works for the meantime. https://github.com/webtorrent/webtorrent/issues/2114#issuecomment-871046916
