### ISSUE TITLE
windows prebuilt missing

### ISSUE THREAD

**Issue by juliangruber** [mafintosh/utp-native#8]
(target=4.5.0 arch=x64 platform=win32)

**Comment by mafintosh** [comment]
SO CLOSE TO MAKING THIS WORK

**Comment by StarpTech** [comment]
Any updates?

**Comment by joehand** [comment]
Current bug is that UTP times out on windows, for example in [this test](https://ci.appveyor.com/project/getsoldat/utp-native/build/1.0.2/job/vqlbsbstn0lb25l9#L134).

**Comment by xoorath** [comment]
Hey,

So far when following this... I've managed to track the issue down to `utp_uv.cc` in `on_utp_sendto`.

The return of `uv_udp_try_send` is [supposed to be >= 0: number of bytes sent](http://docs.libuv.org/en/v1.x/udp.html?highlight=uv_udp_try_send). Instead I'm getting back `-4054` which appears to be [UV__ENOSYS](https://github.com/clibs/uv/blob/master/include/uv-errno.h#L267) which I think is [function not implemented](http://docs.libuv.org/en/v1.x/errors.html?highlight=UV__ENOSYS).

That's where I'm at so far...

**Comment by xoorath** [comment]
Update after discussion with a peer:

> 2 things
> 1. older versions of node's libuv don't have try send implemented, and it throws a function not implemented error (edited)
> 2. after 1 is fix, the remaining issue is scheduled_acks are never sent causing errors
> this comes from a difference between how libuv behaves on posix vs windows
> on posix we get a zero bytes read event, which in turn utp uses to trigger the send of the scheduled_acks
> on windows we never get a zero bytes read event, thus never sending the scheduled_acks
> which puts it in a loop that eventually results in a connection reset error

**Comment by goldbuick** [comment]
I have a rough build that passes all the utp native tests on windows. Going to make a PR when I can

**Comment by joehand** [comment]
YAYAYAY its working. Thank you so much @goldbuick.

**Comment by mafintosh** [comment]
fixed in latest
